reviewers:
  defaults:
    - code-owners
  groups:
    code-owners:
      - Bidon15
      - Ferret-san
      - distractedm1nd
      - YazzyYaz
    celestia:
      - Wondertan
      - S1nus
      - vgonkivs
    devops:
      - smuu
      - sysrex
      - jrmanes
    celestia:
      - team:celestia
files:
  '**':
    - code-owners
    - celestia
  '**/*Dockerfile':
    - devops
  '.github/**':
    - devops
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 3
