reviewers:
  defaults:
    - code-owners
  groups:
    code-owners:
      - Bidon15
      - Ferret-san
      - distractedm1nd
      - jcstein
      - ramin
    celestia:
      - Wondertan
      - S1nus
      - vgonkivs
      - team:celestia
    devops:
      - smuu
      - sysrex
      - jrmanes
files:
  '**':
    - code-owners
    - celestia
  '**/*Dockerfile':
    - devops
  '.github/**':
    - devops
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 2
