name: CI and Release
on:
  push:
    branches:
      - main
    # Trigger on version tags
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-rc(?:[0-9]+|\.[0-9]+)'
  pull_request:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: "Semver type of new version (major / minor / patch)"
        # Input has to be provided for the workflow to run
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      # use consistent go version throughout pipeline here
      GO_VERSION: "1.20"
    outputs:
      go-version: ${{ steps.set-vars.outputs.go-version }}
    steps:
      - name: Set go version
        id: set-vars
        run: echo "go-version=${{env.GO_VERSION}}" >> "$GITHUB_OUTPUT"

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      go-version: ${{ needs.setup.outputs.go-version }}

  test:
    uses: ./.github/workflows/test.yml
    with:
      go-version: ${{ needs.setup.outputs.go-version }}

  # Make a release if this is a manually trigger job, i.e. workflow_dispatch
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    permissions: "write-all"
    steps:
      - uses: actions/checkout@v4
      - name: Version Release
        uses: celestiaorg/.github/.github/actions/version-release@v0.2.8
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          version-bump: ${{inputs.version}}
