# api-equivalence workflow ensures that the API structs between the two repositories are consistent
# This workflow is triggered by ci_release.yml workflow
name: api-equivalence
on:
  workflow_call:
    inputs:
      GO_VERSION:
        description: "Go version to use"
        type: string
        required: true

jobs:
  test-equivalence:
    name: Test API Equivalence
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: celestiaorg/celestia-node
          # TODO: Before mergin this PR, change the ref to use a version tag. Not possible yet because the test doesn't exist currently.
          ref: main
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}

      - name: Run Structs Equivalence Test
        run: cd celestia-node && go test -v -tags=rpcequivalence ./api -run TestStructsEquivalence
