# Tests / Code Coverage workflow
# This workflow is triggered by ci_release.yml workflow
name: Tests / Code Coverage
on:
  workflow_call:
    inputs:
      GO_VERSION:
        description: 'Go version to use'
        type: string
        required: true

jobs:
  go_mod_tidy_check:
    name: Go Mod Tidy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - run: go mod tidy
      - name: check for diff
        run: git diff --exit-code

  test_coverage:
    name: Unit Tests Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: Test & Coverage
        run: make cover
      - uses: codecov/codecov-action@v4.5.0
        with:
          file: ./coverage.txt

  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: execute test run
        run: make test-unit

  unit_race_test:
    name: Run Unit Tests with Race Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: execute test run
        run: make test-unit-race

  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: Integration Tests
        run: echo "No integration tests yet"
